import { useEffect, useMemo, useState } from "react";
import { ActivityIndicator, Modal, ScrollView, StyleSheet, Text, TouchableOpacity, View } from "react-native";
import { MaterialCommunityIcons } from "@expo/vector-icons";
import apiClient from "../../api/client";
import type { WorkoutSession } from "../workouts/types";
import { borderRadius, colors, spacing } from "../../theme";

export default function ImportWorkoutModal({ visible, planDays, onClose, onContinue }: { visible: boolean; planDays: string[]; onClose: () => void; onContinue: (prompt: string) => void }) {
  const [sessions, setSessions] = useState<WorkoutSession[]>([]);
  const [selectedIds, setSelectedIds] = useState<string[]>([]);
  const [targetDays, setTargetDays] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(false);
  useEffect(() => { if (!visible) return; setLoading(true); setSelectedIds([]); setTargetDays({}); apiClient.get("/api/workout-sessions").then((response) => setSessions(Array.isArray(response.data) ? response.data.slice(0, 30) : [])).catch(() => setSessions([])).finally(() => setLoading(false)); }, [visible, planDays.join("|")]);
  const selected = useMemo(() => sessions.filter((session) => session.id && selectedIds.includes(session.id)), [sessions, selectedIds]);
  const toggle = (session: WorkoutSession) => { if (!session.id) return; setSelectedIds((current) => current.includes(session.id!) ? current.filter((id) => id !== session.id) : [...current, session.id!]); setTargetDays((current) => current[session.id!] ? current : { ...current, [session.id!]: planDays.find((day) => day === session.split_day) || planDays[0] || "" }); };
  const ready = selected.length > 0 && selected.every((session) => session.id && targetDays[session.id]);
  const submit = () => { if (!ready) return; const requests = selected.map((session) => { const names = session.exercises.map((exercise) => exercise.exercise_name).filter(Boolean); return `- Use workout ${session.date} as the exact foundation for ${targetDays[session.id!]}. Preserve its ${names.length} exercises in logged order: ${names.join(", ")}.`; }); onContinue(`Import these ${selected.length} logged workouts into my plan:\n${requests.join("\n")}\nKeep weighted and bodyweight versions of the same movement together as coordinated progression tracks. Add supporting exercises only when needed for a complete day, and show me every proposed change before updating my active plan.`); };
  return <Modal visible={visible} transparent animationType="slide" onRequestClose={onClose}><View style={styles.backdrop}><View style={styles.sheet}><View style={styles.header}><View><Text style={styles.title}>Import a Workout</Text><Text style={styles.subtitle}>Use a logged day as the foundation for your plan.</Text></View><TouchableOpacity onPress={onClose} style={styles.close}><MaterialCommunityIcons name="close" size={20} color={colors.textSecondary} /></TouchableOpacity></View>
    {loading ? <ActivityIndicator style={{ margin: 40 }} color={colors.accentPrimary} /> : <ScrollView contentContainerStyle={styles.content}>
      <Text style={styles.label}>1 · CHOOSE WORKOUTS {selected.length ? `(${selected.length} SELECTED)` : ""}</Text>{sessions.length ? sessions.map((session) => { const active = !!session.id && selectedIds.includes(session.id); return <TouchableOpacity key={session.id || `${session.date}-${session.created_at}`} style={[styles.session, active && styles.selected]} onPress={() => toggle(session)}><View style={styles.sessionIcon}><MaterialCommunityIcons name="dumbbell" size={18} color={colors.accentPrimary} /></View><View style={{ flex: 1 }}><Text style={styles.sessionName}>{session.split_day || session.workout_name || session.split_name || "Workout"}</Text><Text style={styles.sessionMeta}>{formatDate(session.date)} · {session.exercises.length} exercises</Text><Text style={styles.exerciseList} numberOfLines={2}>{session.exercises.map((exercise) => exercise.exercise_name).join(" · ")}</Text></View><MaterialCommunityIcons name={active ? "checkbox-marked-circle" : "checkbox-blank-circle-outline"} size={21} color={active ? colors.accentPrimary : colors.textMuted} /></TouchableOpacity>; }) : <Text style={styles.empty}>No logged workouts are available yet.</Text>}
      {selected.length ? <><Text style={styles.label}>2 · ASSIGN EACH WORKOUT</Text>{selected.map((session) => <View key={`assign-${session.id}`} style={styles.assignment}><Text style={styles.assignmentTitle}>{formatDate(session.date)} · {session.split_day || session.workout_name || "Workout"}</Text><View style={styles.days}>{planDays.map((day) => <TouchableOpacity key={day} onPress={() => setTargetDays((current) => ({ ...current, [session.id!]: day }))} style={[styles.day, targetDays[session.id!] === day && styles.daySelected]}><Text style={[styles.dayText, targetDays[session.id!] === day && styles.dayTextSelected]}>{day}</Text></TouchableOpacity>)}</View></View>)}<View style={styles.note}><MaterialCommunityIcons name="shield-check-outline" size={17} color={colors.ai} /><Text style={styles.noteText}>All selected sessions open together in Plan Mode. You’ll review one combined draft before anything changes.</Text></View></> : null}
    </ScrollView>}
    <View style={styles.actions}><TouchableOpacity onPress={onClose} style={styles.cancel}><Text style={styles.cancelText}>Cancel</Text></TouchableOpacity><TouchableOpacity onPress={submit} disabled={!ready} style={[styles.continue, !ready && styles.disabled]}><Text style={styles.continueText}>Import {selected.length || ""} {selected.length === 1 ? "Workout" : "Workouts"}</Text><MaterialCommunityIcons name="arrow-right" size={18} color={colors.onAccent} /></TouchableOpacity></View>
  </View></View></Modal>;
}
function formatDate(value: string) { const date = new Date(`${value}T12:00:00`); return Number.isNaN(date.valueOf()) ? value : date.toLocaleDateString(undefined, { month: "short", day: "numeric", year: "numeric" }); }
const styles = StyleSheet.create({ backdrop:{flex:1,backgroundColor:"rgba(0,0,0,.78)",justifyContent:"flex-end"},sheet:{maxHeight:"92%",backgroundColor:colors.background,borderTopLeftRadius:borderRadius.xl,borderTopRightRadius:borderRadius.xl,overflow:"hidden"},header:{flexDirection:"row",justifyContent:"space-between",alignItems:"flex-start",padding:spacing.lg,borderBottomWidth:1,borderBottomColor:colors.border},title:{fontSize:21,fontWeight:"800",color:colors.textPrimary},subtitle:{fontSize:12,color:colors.textSecondary,marginTop:3},close:{width:34,height:34,alignItems:"center",justifyContent:"center",borderRadius:17,backgroundColor:colors.cardBackground},content:{padding:spacing.lg,paddingBottom:28},label:{fontSize:10,fontWeight:"900",letterSpacing:1,color:colors.textMuted,marginTop:10,marginBottom:9},session:{flexDirection:"row",alignItems:"center",gap:10,padding:13,marginBottom:8,borderWidth:1,borderColor:colors.border,borderRadius:borderRadius.md,backgroundColor:colors.cardBackground},selected:{borderColor:colors.accentPrimary,backgroundColor:"rgba(156,192,232,.07)"},sessionIcon:{width:34,height:34,borderRadius:10,backgroundColor:colors.surface,alignItems:"center",justifyContent:"center"},sessionName:{fontSize:14,fontWeight:"800",color:colors.textPrimary},sessionMeta:{fontSize:11,color:colors.accentPrimary,marginTop:2},exerciseList:{fontSize:10,lineHeight:14,color:colors.textSecondary,marginTop:3},empty:{color:colors.textSecondary,fontSize:13,paddingVertical:20},assignment:{padding:13,marginBottom:9,borderWidth:1,borderColor:colors.border,borderRadius:borderRadius.md,backgroundColor:colors.cardBackground},assignmentTitle:{fontSize:12,fontWeight:"800",color:colors.textPrimary,marginBottom:9},days:{flexDirection:"row",flexWrap:"wrap",gap:8},day:{paddingHorizontal:13,paddingVertical:9,borderRadius:99,borderWidth:1,borderColor:colors.border},daySelected:{backgroundColor:colors.accentPrimary,borderColor:colors.accentPrimary},dayText:{fontSize:12,fontWeight:"700",color:colors.textSecondary},dayTextSelected:{color:colors.onAccent},note:{flexDirection:"row",gap:8,padding:12,marginTop:16,borderRadius:borderRadius.md,backgroundColor:colors.surface},noteText:{flex:1,fontSize:11,lineHeight:16,color:colors.textSecondary},actions:{flexDirection:"row",gap:10,padding:spacing.lg,borderTopWidth:1,borderTopColor:colors.border},cancel:{paddingHorizontal:16,alignItems:"center",justifyContent:"center"},cancelText:{fontSize:13,fontWeight:"700",color:colors.textSecondary},continue:{flex:1,flexDirection:"row",alignItems:"center",justifyContent:"center",gap:7,paddingVertical:13,borderRadius:borderRadius.md,backgroundColor:colors.accentPrimary},disabled:{opacity:.35},continueText:{fontSize:13,fontWeight:"800",color:colors.onAccent} });
