/**
 * Shared Day Blueprint tokens (Slate + Ice default).
 * Keep edit sheets visually tied to the nutrition plan page.
 */
import { Platform, StyleSheet } from "react-native";
import { spacing, borderRadius } from "../theme";

export const bp = {
  accent: "#9CC0E8",
  accentMuted: "#7FA8D0",
  accentSoft: "rgba(156,192,232,0.14)",
  onAccent: "#070708",
  potential: "#E09A45",
  potentialSoft: "rgba(224,154,69,0.16)",
  uncertain: "#A78BFA",
  uncertainSoft: "rgba(167,139,250,0.18)",
  ai: "#5EEAD4",
  aiSoft: "rgba(94,234,212,0.12)",
  surface: "#111113",
  surface2: "#0C0C0E",
  border: "#1C1C1F",
  muted: "#8E8E93",
  muted2: "#636366",
  text: "#FFFFFF",
  danger: "#EF4444",
  page: "#070708",
};

export const bpSerif = Platform.select({
  ios: "Georgia",
  android: "serif",
  default: "serif",
}) as string;

/** Base sheet chrome shared by nutrition plan edit modals. */
export const nutritionSheet = StyleSheet.create({
  backdrop: {
    flex: 1,
    backgroundColor: "rgba(11,12,16,0.78)",
    justifyContent: "flex-end",
  },
  sheet: {
    backgroundColor: bp.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: "92%",
    borderWidth: 1,
    borderColor: bp.border,
  },
  header: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: spacing.lg,
    paddingTop: spacing.lg,
    paddingBottom: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: bp.border,
  },
  title: {
    fontSize: 22,
    fontFamily: bpSerif,
    fontStyle: "italic",
    fontWeight: "500",
    color: bp.text,
  },
  closeBtn: {
    width: 32,
    height: 32,
    borderRadius: 10,
    backgroundColor: bp.surface2,
    borderWidth: 1,
    borderColor: bp.border,
    alignItems: "center",
    justifyContent: "center",
  },
  body: { padding: spacing.lg, paddingBottom: spacing["2xl"], gap: 8 },
  label: {
    fontSize: 11,
    fontWeight: "800",
    color: bp.muted,
    letterSpacing: 0.7,
    textTransform: "uppercase",
    marginTop: spacing.sm,
    marginBottom: 6,
  },
  hint: { fontSize: 12, color: bp.muted2, marginBottom: 8, lineHeight: 16 },
  input: {
    borderWidth: 1,
    borderColor: bp.border,
    borderRadius: borderRadius.md,
    color: bp.text,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
    backgroundColor: bp.surface2,
    fontSize: 14,
  },
  chipRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  chip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderWidth: 1,
    borderColor: bp.border,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: bp.surface2,
  },
  chipOn: {
    borderColor: bp.accent,
    backgroundColor: bp.accentSoft,
  },
  chipText: { fontSize: 12, color: bp.muted, fontWeight: "700" },
  chipTextOn: { color: bp.accent },
  dayChip: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: bp.border,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: bp.surface2,
  },
  dayChipOn: {
    borderColor: bp.accent,
    backgroundColor: bp.accentSoft,
  },
  dayChipText: { color: bp.muted2, fontSize: 12, fontWeight: "800" },
  dayChipTextOn: { color: bp.accent },
  searchBox: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    borderWidth: 1,
    borderColor: bp.border,
    borderRadius: borderRadius.md,
    backgroundColor: bp.surface2,
    paddingHorizontal: spacing.md,
    marginTop: 4,
  },
  searchInput: { flex: 1, color: bp.text, paddingVertical: 12, fontSize: 14 },
  resultRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(42,45,53,0.7)",
  },
  resultName: { fontSize: 14, fontWeight: "600", color: bp.text },
  resultMeta: { fontSize: 12, color: bp.muted, marginTop: 2 },
  pillRow: { flexDirection: "row", flexWrap: "wrap", gap: 6, marginTop: 4 },
  pill: {
    backgroundColor: bp.surface2,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderWidth: 1,
    borderColor: bp.border,
  },
  pillText: { fontSize: 12, color: bp.muted, fontWeight: "600" },
  actions: {
    flexDirection: "row",
    gap: 10,
    padding: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: bp.border,
  },
  primary: {
    flex: 1,
    backgroundColor: bp.accent,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
  },
  primaryDisabled: { opacity: 0.4 },
  primaryText: { color: bp.onAccent, fontWeight: "800" },
  secondary: {
    flex: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: bp.border,
    backgroundColor: bp.surface2,
  },
  secondaryText: { color: bp.muted, fontWeight: "700" },
  deleteBtn: {
    flex: 1,
    borderRadius: borderRadius.md,
    paddingVertical: spacing.md,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(239,68,68,0.4)",
    backgroundColor: "rgba(239,68,68,0.08)",
  },
  deleteText: { color: bp.danger, fontWeight: "700" },
  link: { color: bp.accent, fontWeight: "700", fontSize: 13 },
});
